version: '3.5'

services:
    pulsar:
        command: bin/pulsar standalone
        container_name: pulsar
        depends_on:
            - zookeeper
        dns: 10.1.3.1
        dns_search:
            - ubuntu.home
            - home
        hostname: pulsar.s4.home
        image: ${DOCKER_REGISTRY:-ubuntu-s2.home:5000/}thirdparty/pulsar-all:${PULSAR_VERSION:-2.4.2}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        links:
           - zookeeper
        networks:
            - kafka-net
        ports:
            - "6650:6650"
            - "8080:8080"
        restart: unless-stopped
        volumes:
            - ./pulsar/data:/pulsar/data
            - ./pulsar/logs:/pulsar/logs
            - ./pulsar/log:/var/log

    zookeeper:
#        command: kafka zookeeper
        command: confluent zookeeper
        container_name: zookeeper
        dns: 10.1.3.1
        dns_search:
            - ubuntu.home
            - home
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            JMX_PORT: 1299
            ZOOKEEPER_MY_ID: ${KAFKA_ID:?}
            ZOOKEEPER_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_INIT_LIMIT: 10
            ZOOKEEPER_SYNC_LIMIT: 5
        hostname: zookeeper.s4.home
        image: ${DOCKER_REGISTRY:-ubuntu-s2.home:5000/}${CONTAINER_OS:-alpine}/confluent/${CONFLUENT_VERSION:-5.3.2}:${CONTAINER_TAG:-818d4fb60b137564349d2f7863630162c6f1306aefb03adbb96c2f1568d88b67}
        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "3"
        networks:
            - kafka-net
        ports:
            - "1299:1299"
            - "2181:2181"
        restart: unless-stopped
        volumes:
            - ./zookeeper/data:/usr/local/kafka/data
            - ./zookeeper/logs:/usr/local/kafka/logs 
            - ./zookeeper/log:/var/log

networks:
   kafka-net:
       name: kafka-container-net
