version: '3.5'

services:
    pulsar:
        command: /pulsar/bin/pulsar standalone
        container_name: pulsar
        dns: 10.1.3.1
        dns_search:
            - ubuntu.home
            - home
        hostname: pulsar.s4.home
        image: ${DOCKER_REGISTRY:-ubuntu-s2.home:5000/}thirdparty/pulsar-all:${PULSAR_VERSION:-2.4.2}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        networks:
            - pulsar-net
        ports:
            - "6650:6650"
            - "8080:8080"
        restart: unless-stopped
        volumes:
            - ./pulsar/data:/pulsar/data
            - ./pulsar/logs:/pulsar/logs
            - ./pulsar/log:/var/log

networks:
   pulsar-net:
       name: pulsar-container-net
